sudo: required
dist: trusty
language: csharp
addons:
  hosts:
  - riak-test
env:
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.7/ubuntu/trusty/riak_2.0.7-1_amd64.deb
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.4/ubuntu/trusty/riak_2.1.4-1_amd64.deb
before_script:
- sudo ./tools/travis-ci/riak-install -i -d "$RIAK_DOWNLOAD_URL"
- sudo ./tools/devrel/gen-riak-conf /etc/riak/riak.conf 10018 10017
- sudo ./tools/devrel/strong-consistency-conf /etc/riak/riak.conf
- sudo ./tools/devrel/gen-adv-conf /etc/riak/advanced.config
- sudo ./tools/travis-ci/riak-install -s
- sudo ./tools/devrel/riak-cluster-config "$(which riak-admin)" 10018 true false
script:
  - make test
notifications:
  slack:
    secure: TsPQu/W0Wcn4vtej0mPlD09+Ww7lhaIFbXM5IcdpCKzpsTsx4tP8kTo1VoD/khBqfDLRw9RBDkzFb96ve5607tg0O1LW3ahSNV3gSEMb555fw5Fnb776/aHKb2qQhpXD+eMmqX1dEx1yaiCcKldXmEz8kKolxcU57xjPAQHlzQQ=
